version: "3.9"

services:
  devopsdb:
    image: kanna1208/flm-oct:db
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
    networks:
      - mynetwork

  application:
    image: kanna1208/flm-oct:javapp
    ports:
      - "1111:8080"
    deploy:
      replicas: 3
    depends_on:
      - devopsdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
